### ISSUE TITLE
IDK If this is a bug or not, but I think in the GUI the color you added to text should show.

### ISSUE THREAD

**Issue by jqck3d** [Franckyi/IBE-Editor#13]
In the 1.15.2 version the colored text showed in the GUI, and I think it should also do that in the 1.16.2 version. I am unsure if this was intended or not, so that's why I am making this post. Edit: Forgot to mention the color does show outside of the editor.
![ibeeditor](https://user-images.githubusercontent.com/70854636/92962636-3b1b8e00-f43f-11ea-8776-1479954666fd.png)

**Comment by Franckyi** [comment]
It's funny you opened this issue right now because I was about to push a fix :P Actually it's the way Minecraft handles TextFields that changed and I can't really do anything about it... but on the other hand I can preview the colored text in a tooltip, like so:
![image](https://user-images.githubusercontent.com/17572738/92963067-2c020380-f472-11ea-8e38-c7c4dd9007c7.png)
