### ISSUE TITLE
Crash with Creative mode-only editing disabled

### ISSUE THREAD

**Issue by DalekCraft2** [Franckyi/IBE-Editor#18]
I disabled Creative mode-only editing and attempted to edit an item, and the game immediately crashed. Strangely, it only happens if opening the editor in the inventory GUI, and not whilst holding the item and pressing the key.

**Comment by Franckyi** [comment]
Hi, can you send a crash report?

**Comment by DalekCraft2** [comment]
[crash-2021-04-11_08.24.09-client.txt](https://github.com/Franckyi/IBE-Editor/files/6291728/crash-2021-04-11_08.24.09-client.txt)

**Comment by Franckyi** [comment]
Thanks! You can avoid this crash by closing the Recipe Book. I'll investigate to fix the bug.

**Comment by Franckyi** [comment]
Crash reason: the "key press" event kept propagating to the inventory screen after opening the editor screen, causing a crash when the recipe book is open, due to a NullPointerException after the inventory screen was cleaned up and the recipe book GUI removed. 
Fix: consume (cancel) the event right after opening the editor screen so it doesn't propagate to the inventory screen.

[Fixed in version 1.2.5 (click to download)](https://www.curseforge.com/minecraft/mc-mods/ibe-editor/files/3272500)
