### ISSUE TITLE
[Question] Will this mod be updated to work with the new "components"?

### ISSUE THREAD

**Issue by Mahonzu** [Franckyi/IBE-Editor#94]
Mojang recently changed NBT tags to "Components" in [24w09a](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w09a) and I assume this will break the mod. My question is: will the mod be updated to work with the new system? This mod has saved me a lot of time making custom maps, datapacks, etc. and I would like to continue using it through the new versions of the game.

**Comment by skyecodes** [comment]
I'm aware of those changes. After years of programming on the same old code base, the mod in its current state has become quite difficult to maintain. So I think this Component update will be a good reason to rewrite the mod from scratch.

Just letting you know though, the update will take a while. I'm currently working on other projects and I don't have a lot of time to spend on IBE Editor at this moment. But I'll do everything I can to start working on it before 1.21 gets released so that you don't have to wait for an update for too long.

**Comment by Mahonzu** [comment]
Thanks for your answer! Take your time with the other projects, I appreciate your work. Close this issue if needed

**Comment by Cuteistfox** [comment]
For me too long is after 1.22 as im not that used to these qol mods as i use snapshots
